# Inspecionando tipos de dados
Use o espaço abaixo para explorar os arquivos `data_08.csv` e `data_18.csv` para responder às perguntas do teste abaixo sobre tipos de dados.

In [1]:
import pandas as pd

In [3]:
df_08 = pd.read_csv('data/data_08.csv')
df_18 = pd.read_csv('data/data_18.csv')

# Data 2008

In [4]:
df_08.head()

,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no
1,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,FA,SUV,6,15,20,17,4,no
2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,17,22,19,5,no
3,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,FA,SUV,6,17,22,19,5,no
4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,midsize car,7,16,24,19,5,no

In [7]:
df_08.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2404 entries, 0 to 2403
Data columns (total 14 columns):
model                   2404 non-null object
displ                   2404 non-null float64
cyl                     2205 non-null object
trans                   2205 non-null object
drive                   2311 non-null object
fuel                    2404 non-null object
cert_region             2404 non-null object
veh_class               2404 non-null object
air_pollution_score     2404 non-null object
city_mpg                2205 non-null object
hwy_mpg                 2205 non-null object
cmb_mpg                 2205 non-null object
greenhouse_gas_score    2205 non-null object
smartway                2404 non-null object
dtypes: float64(1), object(13)
memory usage: 263.0+ KB

# Data 2018

In [8]:
df_18.head()

,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,FA,small SUV,3,20,28,23,5,No
1,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,CA,small SUV,3,20,28,23,5,No
2,ACURA RDX,3.5,6.0,SemiAuto-6,4WD,Gasoline,FA,small SUV,3,19,27,22,4,No
3,ACURA RDX,3.5,6.0,SemiAuto-6,4WD,Gasoline,CA,small SUV,3,19,27,22,4,No
4,ACURA TLX,2.4,4.0,AMS-8,2WD,Gasoline,CA,small car,3,23,33,27,6,No

In [9]:
df_18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1611 entries, 0 to 1610
Data columns (total 14 columns):
model                   1611 non-null object
displ                   1609 non-null float64
cyl                     1609 non-null float64
trans                   1611 non-null object
drive                   1611 non-null object
fuel                    1611 non-null object
cert_region             1611 non-null object
veh_class               1611 non-null object
air_pollution_score     1611 non-null int64
city_mpg                1611 non-null object
hwy_mpg                 1611 non-null object
cmb_mpg                 1611 non-null object
greenhouse_gas_score    1611 non-null int64
smartway                1611 non-null object
dtypes: float64(2), int64(2), object(10)
memory usage: 176.3+ KB